### ISSUE TITLE
streamlit_app can't find model_db

### ISSUE THREAD

**Issue by ghost** [i-dot-ai/redbox#184]
After bringing up the backend with the streamlit front end, Streamlit can't find model_db. 

It looks like utils.py is missing some bits that should point it to core-api rather than its own models.

**To Reproduce**

```console
docker compose up core-api ingester embedder streamlit_app
```

Go to `localhost:8501`.

```text
2024-04-05 08:35:11 
2024-04-05 08:35:11 Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
2024-04-05 08:35:11 
2024-04-05 08:35:13 
2024-04-05 08:35:13   You can now view your Streamlit app in your browser.
2024-04-05 08:35:13 
2024-04-05 08:35:13   URL: http://0.0.0.0:8501
2024-04-05 08:35:13 
2024-04-05 08:37:26 2024-04-05 07:37:26.035 Uncaught app exception
2024-04-05 08:37:26 Traceback (most recent call last):
2024-04-05 08:37:26   File "/app/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
2024-04-05 08:37:26     exec(code, module.__dict__)
2024-04-05 08:37:26   File "/app/Welcome.py", line 2, in <module>
2024-04-05 08:37:26     from utils import init_session_state
2024-04-05 08:37:26   File "/app/utils.py", line 28, in <module>
2024-04-05 08:37:26     from model_db import SentenceTransformerDB
2024-04-05 08:37:26 ModuleNotFoundError: No module named 'model_db'
```

**Expected behaviour**

Streamlit should use the core-api.

**Comment by gecBurton** [comment]
https://github.com/i-dot-ai/redbox-copilot/pull/185

**Comment by gecBurton** [comment]
@wpfl-dbt https://github.com/i-dot-ai/redbox-copilot/pull/185 is now closed. this-works-on-my-machine :tm:, if it works for you I will close the issue
